version: "3"

services:
  wordpress:
    image: wordpress:${WORDPRESS_IMAGE}
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      web_net:
        ipv4_address: 172.20.0.2

  db:
    image: mariadb:${MARIADB_IMAGE}
    restart: always
    environment:
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      web_net:
        ipv4_address: 172.20.0.3

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db
    networks:
      web_net:
        ipv4_address: 172.20.0.4

  nginx:
    image: nginx:${NGINX_IMAGE}
    ports:
      - ${NGINX_PORT_80}:80
      - ${NGINX_PORT_443}:443
      - ${CROWDSEC_DASHBOARDPORT}:3000
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/logs/:/var/log/nginx
    depends_on:
      - wordpress
    restart: always
    networks:
      web_net:
        ipv4_address: 172.20.0.5


  crowdsec:
    image: crowdsecurity/crowdsec
    restart: always
    environment:
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID-1000}"
    depends_on:
      - 'nginx'
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/crowdsec-config/acquis.d/:/etc/crowdsec/acquis.d/
      - ./nginx/logs:/var/log/nginx
      - /var/log/auth.log:/var/log/auth-host.log
      - /var/log/syslog:/var/log/syslog-host
      - ./crowdsec/crowdsec-db:/var/lib/crowdsec/data/
      - ./crowdsec/crowdsec-config:/etc/crowdsec/
    networks:
      web_net:
        ipv4_address: 172.20.0.6

  dashboard:
    build: ./crowdsec/dashboard
    restart: unless-stopped
    environment:
      MB_DB_FILE: /data/metabase.db
      MGID: "${GID-1000}"
    depends_on:
      - 'crowdsec'
    volumes:
      - ./crowdsec/crowdsec-db:/metabase-data/
    networks:
      web_net:
        ipv4_address: 172.20.0.7

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      web_net:
        ipv4_address: 172.20.0.8

networks:
  web_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
